trigger:
  - master

pr:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      sudo apt-get install -y python3-venv
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: . venv/bin/activate && python --version
    displayName: 'Discover python version'

  - script: . venv/bin/activate && pylint sodigest
    displayName: 'Lint'
