trigger:
  - master

pr:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: printenv
    displayName: 'Test environment'
