trigger:
  - master

pr:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: sudo apt-get install -y devscripts debhelper python3-all python3-setuptools
    displayName: 'Build server requirements'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: |
      pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: pylint sodigest
    displayName: 'Lint'

  - script: ./run_tests.sh
    displayName: 'Unit tests'
