trigger:
  - master

pr:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: sudo apt-get install -y devscripts debhelper python3-all python3-setuptools
    displayName: 'Build server requirements'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: |
      pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: pylint sodigest
    displayName: 'Lint'

  - script: ./run_tests.sh
    displayName: 'Unit tests'

  - script: ./deb_build.sh
    displayName: 'Build deb'

  - script: cp ../stackoverflow-digest_0.1.1_amd64.deb $(Build.ArtifactStagingDirectory)
    displayName: 'Copy deb pkg'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish deb pkg'
