trigger:
  - master

pr:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: |
      pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: pylint sodigest
    displayName: 'Lint'

  - script: ./run_tests.sh
    displayName: 'Unit tests'

  - script: ./deb_build.sh
    displayName: 'Build deb'
